#!/bin/bash
#
#SBATCH --get-user-env
#SBATCH -t 3-0:00
#SBATCH --gres=gpu:1

singularity exec -B $SINGULARITY_BIND_CODE:$SINGULARITY_BIND_CODE -B $SINGULARITY_BIND_DATA:$SINGULARITY_BIND_DATA --env PYTHONPATH=$PYTHONPATH:$SIM_FOLDER --nv $SIM_FOLDER/d3rlpy.sif python $DEEP_RL_FOLDER/run.py $DATA_SAVE_FOLDER $SIM_NUM $N_ITERS $MODEL_TYPE $REWARD $N_STEPS $N_FOLDS
