"""Script to calculate outcomes using simulation setup from predicted policies generated by R methods from the
DynTxRegime R package. Must run the DynTxRegime.R script in this folder before running this.

Created on October 16, 2023
@author: anonymous
"""
import pandas as pd
import sys

from sim_helpers import calc_outcome

_, file_path, sim_num, iter_num, method = sys.argv

file_path = f'{file_path}/sim_{sim_num}_iter_{iter_num}'

df = pd.read_csv(f'{file_path}_df_obs.csv')
df = df[[c for c in df.columns if 'X' in c]]
burdens = pd.read_csv(f'{file_path}_{method}_burdens.csv').drop(columns=['Unnamed: 0'])
concentrations = pd.read_csv(f'{file_path}_{method}_concentrations.csv').drop(columns=['Unnamed: 0'])

outcomes = []
for i in range(df.shape[0]):
    outcomes.append(
        calc_outcome(df.loc[i].to_numpy(),
                     burdens.loc[i].dropna().to_numpy(),
                     concentrations.loc[i].dropna().to_numpy())
    )

pd.DataFrame(outcomes, columns=[method]).to_csv(f'{file_path}_{method}_outcomes.csv', index=False)
